# docker build --file Dockerfile.build .

FROM debian:bookworm

RUN apt-get update \
  && apt-get --assume-yes install \
  build-essential cmake pkg-config debhelper libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc \
  libboost-program-options-dev

WORKDIR /tmp/
COPY . /tmp/

RUN dpkg-buildpackage -j4 && for deb in ../*.deb; do dpkg --contents $deb; done

# output:
# /grpc-server_1.1.0_amd64.deb
# /grpc-client_1.1.0_amd64.deb