# docker build --file Dockerfile.build .

FROM debian:buster

RUN apt-get update \
  && apt-get --assume-yes install \
  pbuilder aptitude cmake pkg-config

WORKDIR /tmp/
COPY . /tmp/

RUN /usr/lib/pbuilder/pbuilder-satisfydepends
RUN dpkg-buildpackage -j4 && for deb in ../*.deb; do dpkg --contents $deb; done

# output:
# /grpc-server_1.1.0_amd64.deb
# /grpc-client_1.1.0_amd64.deb