apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-grpc-server-90ms
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: fb-grpc-server-90ms
  template:
    metadata:
      annotations:
        team: "fboranek"
      labels:
        app: fb-grpc-server-90ms
        track: stable
    spec:
      containers:
      - name: fb-grpc-server-90ms
        image: fboranek/grpc-server:1.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8442
        resources:
          requests:
            cpu: 1
            memory: 100Mi
          limits:
            cpu: 2
            memory: 200Mi
        env:
        - name: GRPC_SERVER_DELAY_REQUEST_MS
          value: '90'
        - name: GRPC_SERVER_ECHO_MESSAGE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
